config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  private
  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picgur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>
<p>
  <%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<h1>Picgur (<%= @pictures.length %> pictures)</h1>
<p>
  <%= link_to "post a picture", new_picture_path %>
</p>

<% @pictures.each do |picture| %>
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
  <p> <span style="color: blue;">@<%= picture.artist %></span> <%= picture.title %></p>
  <br>
  <br>
  <br>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<%= link_to 'Back to Pictures', pictures_path %>

<%= form_for @picture do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/show.html.erb
<h1>Show picture</h1>
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"}  %>
<br>
<br>
<img src="<%= @picture.url %>" />
<p> <span style="color: blue;">@<%= @picture.artist %></span> <%= @picture.title %></p>